[connections.supabase]
url = "https://njxzqyinqqujgjdkefpl.supabase.co"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qeHpxeWlucXF1amdqZGtlZnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzY3MTcsImV4cCI6MjA4NzM1MjcxN30.xK8yJ38Eazpyn_tvXCE7NcCog9WgYpcXraPkamvFMvM"
